version: '2.0'

services:
  snapshot:
    image: jpccr.ccs.tencentyun.com/llm-town/mud-ecs-snapshot:0.1.0
    entrypoint:
      - /service/ecs-snapshot
    command:
      - -ws-url=wss://follower.testnet-chain.linfra.xyz
      - -port=8546
      - -snapshot-block-interval=600
      - -initial-sync-block-batch-size=1000
      - -initial-sync-block-batch-sync-timeout=20
      - -worldAddresses=0xE9982992AA4216fa02Ae2D026fc9Fd14Fc0c83D9
      - -block=17363638
    ports:
      - "8547:8547"
    restart: always

volumes:
  anvil-data: